# FIDL interface and deployment files
filegroup(
    name = "fidl_files",
    srcs = [
        "HelloWorld.fidl",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "fdepl_files",
    srcs = [
        "HelloWorld.fdepl",
    ],
    visibility = ["//visibility:public"],
)
